export const ModalKeys = {
  GENERAL_MESSAGE: "GENERAL_MESSAGE",

  ADD_CLIENT: "ADD_CLIENT",
  UPDATE_CLIENT: "UPDATE_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",

  ADD_ACCOUNT: "ADD_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
};

export const PaginationKeys = {
  CLIENT: "CLIENT",
  ACCOUNT: "ACCOUNT",
};

/**
 * CUD stand for Create Update Delete
 */

export const LoadingKeys = {
  LOADING_CLIENT: "LOADING_CLIENT",
  LOADING_CUD_CLIENT: "LOADING_CUD_CLIENT",

  LOADING_ACCOUNT: "LOADING_ACCOUNT",
  LOADING_CUD_ACCOUNT: "LOADING_CUD_ACCOUNT",

  LOADING_LOGIN: "LOADING_LOGIN",
};
