export const ModalKeys = {
  GENERAL_MESSAGE: "GENERAL_MESSAGE",

  ADD_CLIENT: "ADD_CLIENT",
  UPDATE_CLIENT: "UPDATE_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",

  ADD_ACCOUNT: "ADD_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",

  ADD_PROJECT: "ADD_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  ADD_INVOICE: "ADD_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  UPDATE_INVOICE: "UPDATE_INVOICE",
};

export const PaginationKeys = {
  CLIENT: "CLIENT",
  ACCOUNT: "ACCOUNT",
  PROJECT: "PROJECT",
};

/**
 * @field CUD stand for Create Update Delete
 */
export const LoadingKeys = {
  LOADING_CLIENT: "LOADING_CLIENT",
  LOADING_CUD_CLIENT: "LOADING_CUD_CLIENT",

  LOADING_ACCOUNT: "LOADING_ACCOUNT",
  LOADING_CUD_ACCOUNT: "LOADING_CUD_ACCOUNT",

  LOADING_PROJECT: "LOADING_PROJECT",
  LOADING_CUD_PROJECT: "LOADING_CUD_PROJECT",

  LOADING_INVOICE: "LOADING_INVOICE",
  LOADING_CUD_INVOICE: "LOADING_CUD_INVOICE",

  LOADING_LOGIN: "LOADING_LOGIN",
};
